### ISSUE TITLE
can get site but cannot select

### ISSUE THREAD

**Issue by Condorello** [danieldotnl/hass-multiscrape#4]
Hello.
I'm trying to select some field from my weather station. Seems to can retrive the htm page looking in the logs, but the select return blank. Or maybe it return something, but cannot decoded, anyway the sensor value is blank.

Here my sensor config:
```
  - platform: multiscrape
    name: home_scraper
    resource: http://192.168.1.65/livedata.htm
    scan_interval: 30
    verify_ssl: false
    selectors:
      provameteo:
        name: Temp Out
        select: "tr:nth-of-type(11) input"
        unit_of_measurement: '°C'
        value_template: "{{ value.split('value=')[1].split('\"')[1] | float }}"
```

i also tried with another value_template, which is simpler, but cannot solve anything also with this:

`        value_template: '{{ value[111:114] }}'
`

here the debug log which seems ok:
`2021-01-06 12:16:05 DEBUG (MainThread) [custom_components.multiscrape.sensor] Response from http://192.168.99.65/livedata.htm:
<ClientResponse(http://192.168.99.65/livedata.htm) [200 OK]>
<CIMultiDictProxy('Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'Content-Type': 'text/html')>
2021-01-06 12:16:05 DEBUG (MainThread) [custom_components.multiscrape.sensor] Sensor Temp Out selected:
2021-01-06 12:16:05 DEBUG (MainThread) [custom_components.multiscrape.sensor] Finished fetching multiscrape data in 1.302 seconds
2021-01-06 12:16:06 DEBUG (MainThread) [custom_components.multiscrape.sensor] Response from http://192.168.99.65/livedata.htm:
<ClientResponse(http://192.168.99.65/livedata.htm) [200 OK]>
<CIMultiDictProxy('Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'Content-Type': 'text/html')>
2021-01-06 12:16:06 DEBUG (MainThread) [custom_components.multiscrape.sensor] Sensor Temp Out selected:
2021-01-06 12:16:06 DEBUG (MainThread) [custom_components.multiscrape.sensor] Finished fetching multiscrape data in 0.888 seconds`

I tried to write a very basic python script to run on the hass os directly, which works fine and select something:
`from bs4 import BeautifulSoup
import requests
URL="http://192.168.99.65/livedata.htm"
SELECT="tr:nth-of-type(11) input"

r = requests.get(URL)
data=r.text

raw_data = BeautifulSoup(data, "html.parser")

print(raw_data)

val = raw_data.select(SELECT)

print("Output of SELECT: **************")
print(val)
print("**************")`

how can i investigate further?
